.TH TOULBAR2 1
.SH NAME
toulbar2 \- sexactly solves discrete optimization problems on graphical models
.SH SYNOPSIS
.B toulbar2
[options] 
.IR file
.SH DESCRIPTION
.B toulbar2
solves discrete optimization problems defined by a graphical model
including Cost Function Networks or Weighted Constraint Satisfaction
Problems, Markov Random Fields (Maximum A Posteriori or MAP/MRF),
Bayesian Networks (Maximum Probability Explanation or MPE/BN),
Quadratic Pseudo Boolean Optimization Problems (QPBO or MAXCUT),
Partial Weighted Maximum Satisfiability...

.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.

.SH EXAMPLES
To write some text to the standard output, use the
.BR printf (1)
command:
.PP
.nf
.RS
printf "this is a %s format %s\n" \\
usual string
.RE
.fi
.PP
Nifty, huh?

.SH AUTHOR
Vivek Gite (vivek@nixcraft.net.in)
