###############################################################################
# 
#                     Dockerfile_toulbar2 container 
# 
#           including toulbar2 and its pytoulbar2 Python API
# 
# Desc ------------------------------------------------------------------------
# 
# Installation from sources with cmake options -DPYTB2=ON and -DXML=ON
# 
# Build -----------------------------------------------------------------------
#
# To build toulbar2-docker image :
#
#   docker build -f Dockerfile_toulbar2 -t toulbar2-docker:latest .
#
# Work inside -----------------------------------------------------------------
#
# Then to work inside toulbar2-docker image, under /WORK 
# (as local folder to remaining results) :
#
#   docker run -v $PWD:/WORK -ti toulbar2-docker /bin/bash
#
#   and once inside : source /WORK.sh
#
###############################################################################

FROM debian:trixie-slim

RUN apt-get update -yq \
&& apt-get install git-core -y \
&& apt-get install vim -y \
&& apt-get install cmake -y \
&& apt-get install g++ -y \
&& apt-get install libgmp-dev -y \
&& apt-get install libboost-graph-dev -y \
&& apt-get install libboost-iostreams-dev -y \
&& apt-get install zlib1g-dev -y \
&& apt-get install liblzma-dev -y \
&& apt-get install libxml2-dev -y \
&& apt-get install libopenmpi-dev -y \
&& apt-get install libjemalloc-dev -y \
&& apt-get install pkg-config -y \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& apt-get install bc -y \
&& pip3 install pybind11[global] --break-system-packages \
&& apt-get clean -y

RUN git clone https://github.com/toulbar2/toulbar2.git

RUN cd toulbar2 \
&& mkdir build \
&& cd build \
&& cmake -DPYTB2=ON .. \
&& make -j5

RUN cp /toulbar2/build/lib/Linux/pytb2.cpython-*-x86_64-linux-gnu.so /toulbar2/pytoulbar2/pytb2.cpython-*-x86_64-linux-gnu.so

RUN CMDFILE=/WORK.sh \
&& echo "#!/bin/bash" > $CMDFILE \
&& chmod 755 $CMDFILE \
&& echo "#####################################################" >> $CMDFILE \
&& echo "# Init to work into /WORK folder with (py)toulbar2   " >> $CMDFILE \
&& echo "#####################################################" >> $CMDFILE \
&& echo "PATH=\$PATH:/toulbar2/build/bin/Linux:/toulbar2/src:/WORK" >> $CMDFILE \
&& echo "ln -s /toulbar2/pytoulbar2 /WORK/pytoulbar2"           >> $CMDFILE \
&& echo "cd /WORK"                                              >> $CMDFILE


###############################################################################

