#!/bin/bash

# usage: mzn2py problem.mzn problem.dzn

# mzn2fzn -I ./mznlib --output-to-stdout $* | ./fzn2py -

pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do cd `dirname "$SCRIPT_PATH"`; SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

MZNNJ_DIR=$SCRIPT_PATH

SED='sed -r'
if [[ "$(uname)" == "Darwin" ]]; then
    # The version of sed on Mac has a different option to enable extended regular expressions
    SED='sed -E'
fi

param1=${*##*.dzn}
param=${param1##*.mzn}
problem=`echo "$*" | $SED 's/ -.*//'`
minizinc -c -O3 --solver ${SCRIPT_PATH}/toulbar2.msc -I ${MZNNJ_DIR}/mznlib --no-output-ozn --output-to-stdout $problem | ${MZNNJ_DIR}/fzn2py - | tee problem.py | python - $param
