###################"

# property personnalisé for -D Option

#############

	IF(WIN32)
#add_definitions(-DWIN32 -D_DEBUG -D_WINDOWS -D_USRDLL )
#add_definitions(-D__MINGW32__)

IF(TOULBAR2)
	set_property(
			TARGET toulbar2${EXE}
			PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  INT_COST  WIN32 _DEBUG _WINDOWS WINDOWS 
		    )
ENDIF(TOULBAR2)

IF(MENDELSOFT)
	set_property(
			TARGET mendelsoft${EXE}
			PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  INT_COST MENDELSOFT  WIN32 _DEBUG _WINDOWS WINDOWS

		    )
ENDIF(MENDELSOFT)

IF(LIBTB2)
	set_property(
			TARGET tb2
			PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  ${COST}
		    )
# PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  LONGLONG_COST -fPIC

ENDIF(LIBTB2)

ELSE(WIN32)

IF(TOULBAR2)
	    MESSAGE(STATUS "####DEFINE OPTION ==> COST= ${COST}  XMLFLAG= ${XMLFLAG} BOOST = ${boostflag}##########################")
	set_property(
			TARGET toulbar2
			PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  ${COST} ${XMLFLAG} LINUX ${boostflag}
		    )
ENDIF(TOULBAR2)

IF(MENDELSOFT)
	set_property(
			TARGET mendelsoft
			PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY   ${COST} MENDELSOFT LINUX
		    )
ENDIF(MENDELSOFT)

IF(LIBTB2)
	set_property(
			TARGET tb2
			PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  ${COST} LINUX
		    )
# PROPERTY COMPILE_DEFINITIONS NARYCHAR WCSPFORMATONLY  LONGLONG_COST -fPIC

ENDIF(LIBTB2)

IF(LIBTB2INT)
	set_property(
			TARGET tb2int
			PROPERTY COMPILE_DEFINITIONS INT_COST ILOGLUE IL_STD LINUX
		    )

ENDIF(LIBTB2INT)

if(ILOG)
	set_property(
			TARGET iloglue
			PROPERTY COMPILE_DEFINITIONS INT_COST ILOGLUE IL_STD  LINUX
		    )

ENDIF(ILOG)


ENDIF(WIN32)
