#list instance is a double entry list"
# the current file must include"
# one set named instances  (with the list of the array of option"

#each element include into $instance set  allow to declare an set of option corresponding to the given element"
# example if the set instances contain only : foo.wcsp  you must define a second set named foo.wcsp where you will"
# define the list of option ( each element of the second list "foo.wcsp will be used for create a unit test"
# on foo.wcsp with option declare on each tuple of the foo.wcsp (set)

SET (instances 
	CELAR6-SUB0.wcsp CELAR6-SUB1.wcsp pedigree1.wcsp 10_1.bep CELAR7-SUB0.wcsp  )

#please beware to space 
# remove multiple space separtor between argument if there are not required 

SET (CELAR6-SUB0.wcsp
    "-A"
    "-A -S -ub=160"
    "-A -V"
    "-A -V -ub=160"
    "-A=10 -V"
    "-A=10"
    "-A=10 -V"
    "-A=10 -v"
    "-B=0"
    "-B=1"
    "-B=1 -Z"
    "-B=1 -Z -R=1"
    "-B=2"
    "-B=3"
    "-O=CELAR6-SUB0.mcs.order -B=1"
    "-O=CELAR6-SUB0.mcs.order -B=1 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=1 -Z -R=1"
    "-O=CELAR6-SUB0.mcs.order -B=1 -Z -R=2"
    "-O=CELAR6-SUB0.mcs.order -B=1 -Z -R=3"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=2"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=2 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=3 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=4 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=5"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=5 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=2"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=3"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=3 -E"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=3 -R=0"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=3 -R=1"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=3 -R=2"
    "-O=CELAR6-SUB0.mcs.order -B=1 -r=6 -Z -X=3 -R=4"
    "-O=CELAR6-SUB0.mcs.order -B=2 -j=1"
    "-O=CELAR6-SUB0.mcs.order -B=2 -j=1 -Z"
    "-O=CELAR6-SUB0.mcs.order -B=2 -j=1 -k=1 -Z"
    "-h -t -i"
    "-h -t -ub=160"
    "-h -ub=160"
    "-w"
    "-x"
    "-x=,1=1,2=1"
    "-z"
    "-z=2"
   CELAR6-SUB0.mcs.order
   "CELAR6-SUB0.mcs.order -B=1" 
   "CELAR6-SUB0.mcs.order -v=1" 
   "${PROJECT_SOURCE_DIR}/cover/CELAR6-SUB0.sol"
   "${PROJECT_SOURCE_DIR}/cover/CELAR6-SUB0.sol -x"
    "-A -C=10"
    "-A -S"
    "-A -S -ub=3230"
    "-A -C=10"
    "-A=10"
    "-A=10 -v"
    "-A=10 -v=1"
    "-A=10 -v=1 -T=10"
    "-A=10 -v=1 -T=10 -C=10"
    "-A=10 -v=1 -T=10 -h"
    "-Z"
    "-Z -v=1"
    "-Z -v=2"
    "-Z=2 -v=1"
    "-Z=3 -v=1"
    "-v=1"
    "-v=2"
    "-w"
    "-x"
    "-x=sol"
)
SET (pedigree1.wcsp
    "-b"
    "-b:"
    "-b: -v"
    "-b: -v=1"
    "-b: -v=1"
    "-e"
    "-e:"
    "-e=2"
    "-e=3"
    "-h"
    "-h -t -i"
    "-h -t -k=1"
    "-h -t -k=2"
    "-h -t -k=3"
    "-h -t -o"
    "-h -t -ub=76911690 -i"
    "-h=4"
    "-q: -e"
    "-t -h"
    "-ub=1000"
    "-ub=1000000"
    "-ub=10000000"
    "-ub=76911689"
    "-v=1"
)
SET (10_1.bep
    "-e:"
    "-e: -s"
    "-v=2"
)


SET (CELAR7-SUB0.wcsp 
    "-A"
    "-A -M=100"
    "-A=10 -C=1"
    "-V -A=10 -C=1"
    "-A -S"
    "-A -S -ub=3230"
    "-A -C=10"
    "-A=10"
    "-A=10 -V"
    "-A=10 -v"
    "-A=10 -v=1"
    "-A=10 -v=1 -T=10"
    "-A=10 -v=1 -T=10 -C=10"
    "-Z"
    "-Z -v"
    "-Z -v=1"
    "-Z -v=2"
    "-Z=2 -v=1"
    "-Z=3 -v=1"
    "-v=1"
    "-w"
    "-x"
    "-x=sol"
    "-A"  
    "-A -M=100"
    "-A -V"
    "-A=10 -C=1"
)

SET (zebre-ext.wcsp
    "-D"
    "-a"
    "-a -B=1"
    "-a -B=1 -D"
    "-D"
    "-a"
    "-a -B=1"
    "-a -B=1 -D"
)
