name: pytoulbar2_final

on:
  push:
    tags:
      - 'pytb2-v*'  

  workflow_dispatch: # debug

jobs:

  pytb2-linux:
    if: false
    name: pytoulbar2-linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:

          CIBW_BEFORE_ALL: "yum -y install bc gmp-devel boost169-devel zlib-devel bzip2-devel xz-devel"

          CIBW_BEFORE_BUILD: "pip install -r dev-requirements.txt"

          CIBW_ENVIRONMENT: BOOST_INCLUDEDIR=/usr/include/boost169 BOOST_LIBRARYDIR=/usr/lib64/boost169
          
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"

          CIBW_SKIP: "*-manylinux_i686* *-musllinux*"

          CIBW_BUILD_VERBOSITY: 1

          CIBW_TEST_REQUIRES: pytest

          CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && cp {package}/validation/default/example.wcsp ./ && pytest ./tests"

      - uses: actions/upload-artifact@v4
        with:
          name: pytoulbar2-linux
          path: ./wheelhouse/*.whl



  pytb2-macos-x86_64:
    if: false
    name: pytoulbar2-macos-x86_64
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=13
 
          CIBW_BEFORE_ALL: "brew install cmake gmp zlib xz boost"

          CIBW_BEFORE_BUILD: "pip install -r dev-requirements.txt"

          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"

          CIBW_BUILD_VERBOSITY: 1

          CIBW_TEST_REQUIRES: pytest

          CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && cp {package}/validation/default/example.wcsp ./ && pytest ./tests"

      - uses: actions/upload-artifact@v4
        with:
          name: pytoulbar2-macos-x86
          path: ./wheelhouse/*.whl



  pytb2-macos-arm:
    if: false
    name: pytoulbar2-macos-arm
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:

          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=14 CMAKE_APPLE_SILICON_PROCESSOR=arm64

          # to be installed outside of python env
          CIBW_BEFORE_ALL: "brew install cmake gmp zlib xz boost"

          CIBW_BEFORE_BUILD: "pip install -r dev-requirements.txt"
          
          HOMEBREW_NO_AUTO_UPDATE: 1
          
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"

          CIBW_BUILD_VERBOSITY: 1

          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "cp -r {package}/pytoulbar2/tests ./ && cp {package}/validation/default/example.wcsp ./ && pytest ./tests"

      - uses: actions/upload-artifact@v4
        with:
          name: pytoulbar2-macos-arm
          path: ./wheelhouse/*.whl

  publish:
    if: false
    name: Upload release to PyPI
    needs: [pytb2-linux, pytb2-macos-x86_64, pytb2-macos-arm]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pytoulbar2
    permissions:
          id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:

      - uses: actions/download-artifact@v5
        with:
          path: artifacts

      - shell: bash
        working-directory: artifacts
        run: mkdir ../dist && cp */*.whl ../dist
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1



